'use strict';
const string = 'ayayrnhxvfbxzodsycpjqlrbwbmrmoaeunllzjrtdcmdbcmbdefglycboqxkagyderwkpdpewsjgkqdhcsixxhsrolrfnbkilw\nwgfvoecyrmvjefplndcdrozkpkoxnigzpcgzzeitwddxtqrhfqsukchfxqycacmoiknbiwhxxmbpljqhkahjt\nrbharxcldxthzuqrmofxcomdvjewxvwpsyhdnyamglki\nhjtcaklozqfqdhegxprswinviyumb\ntkpypsgvxridahechuimlgzbszkwjqofikegrfnc\nbpxujjbamtbayygucpdubwjqchiixesgaxfsoyveixdudaimkmbjpsvqhjjhdzdmpctwqfvpnydsrphinuwlnxns\ndhqdtxtqmjpljdcvsbbxycjgvjgdwuawifiarpovyvuegjunrfwkiezevniawwj\niakgmjufocwzvckqgrblosihzoallnxpkfrddewuugbfcheepnssbodotlwmerspnrkutwjfpvjmyznyxahlemuosfxwwqcrpnil\ntuwrztdwcnixcmnthwfpqvobumirefolsyutfjsbcrymcnkguetxxpvqgnuupilfacg\nauwsniqazoujcwrhgmydxtqtdodeqxhjvdrwecllpgobpyhhmwzbxnjufhejvnrkbkcvgfrlnwcsvitkdeiwwvoyvu\nzqbrrwhredbkhpifuugdlsoctjqnmavivmxly\nvwfhdyvrpesrrzsbdzazfelvkoxkjmbpuchrlukfpyuiwltpgyijoxlhuqffyabnzcgjpcnrwxhjbpgduaqeicdfu\njmxunyoixyqkwqzcjvapzualqsfxsdejrvwsdnrlyzcagcjmskntpscosnkuzhbpnodrdyvccfjfzkmcutbianzmgrgqde\npemtwacnulonrfqivxsuqvjtydvzkhbgbx\nwssqhzlgzqiolfyfrmslcsemodxmfonzekuenqkhnpfhmcssojhkbpantwvedakogcqohsuyl\ntvhfdoltzrarjgwcmhfxtihgcnoniovktrzrastgacyztobfwmpibkotkoqbgjdfuyenveabpbhap\nqfezrjtualblytkmiiynkssgiawedxobpzhcmwvf\nkunvirnaxglbzvwdigzonasnmlefufxthlvmjmwcvyquuopqy\nsrxexnbcafbyzfpookleaqmouctszcqinvrmyomfaivahwqitdpkhcgxgvhqiqqbynmljgjeqyvxbmbnxrqjmau\nammqkvpptlborkerralkzxoacygliubggvumelrxtinbsufwahekgcfvwttpqqqxzwspcjrde\nprhefnqfgzrojyedwpaampontkyghlweicuxlbqfvuars\nqtihdwshwpnojovcrunasdkjjvgxqmgzwmqmpgrcakfjylwextpobkkntxxceiupzubuoiaqecis\nrkfenjmobutlqwqsdgpiapchyxvzl\nihjrfqtgzcynaszvdseeaddvylhyneypqpungdddzretiavlaykfykjoyxoxlqjymwgjxedrldb\nusakrhosijzciglpgvtmqqrnfdunzqntbtkoeopwxlsegsmodiqaferxyro\npcdqugnvbrtaikyjeonmyekssxutoidhyldzzwjf\nhpcdtwwocixiastzqvqvbwfkvfktgchdajoyxrbxfmexudaiwjskrufbbasbmjufxqjvejauklafpkcivunxy\nqkqcialfsqhkzmgqssiiehvxiwoyenaghnndoqhlmuodobgpgrgpolrzmzmtuqhwhkdkjwfpauqxxbdwwanv\ntahbfoqjhhyjwociqvptkuifrlmziiqktsdnpilgdexazmkbxm\ncujhiwsvsptysoybzlipcgiwqtcvvyvvobxohdlpkujzqtdnqemgxocfpazxrhqcnldy\nionolubaqmqyuhvsktigmetfnghjdcgvywziqpgmtutmxjbrnyiqhh\nhpeouucdzrvjovhzrtykwdgzbvxgextswhxvvwufqrxdlrdomiznfarqslmqciqaywlzckotdq\ndivdoncdlkcgihpuurbicfybfkzkdszdyhqwncmvyozqqjprhloosredxymvldubqdndmwtvggrcat\nsuhrpnpuipcbgtrbilowodsvfzutflcvzpesimcianxefaqsnohhlmbdjdnfdxgwkfzgijyqzkw\nadmcwveyqdgrluiswaawfqmsngulzoonvcrjzvhikxebntrkjjhpzauogkt\ndvnvpiugvvusjahtsrecuylbamkvmfhjouznqvvawxmv\nawvlucnhyozgqpjltdiobrxfkemsftppa\ncmfgtxqowqzczmbltkznsldmxzthnlvkazeiiqfbcjvopysaeru\nqxhoigvvlhbdpetzzpccxptobeuafbynmszkjjjfayndarswkrscmp\necdevhmdikfyujafjzhyzkrqvferrmjwytmofcitwpjsqvjwicokbdpclzgzsnlrbfgabdoxbsvoqwanmmmypjizo\nyfndihlzocgmxabsktupjevhzwrwq\nrejqymhqvqfwajqtsqvtoiqnctmbbxsbkntqcaewkzakhmfrsxhlpzzqiruynfxusojuygggiefzstikmcbhhzvxtudf\nzytvjztzyjwrzvuscxaishplniotuorbjukrhpjsxgdhmmgsecwqpinqbffpbdhknocexidozrvqtmiocwhq\nvhhycyncgxodfmiingnlgqzrukxukzdtaczallisxzsjqialdahofsltgbhpdvejwcmzigncctwtje\nflzvgpaotyboifihguidmtkxewctgvnwkjnxhvseerleydprmqeli\nojdtqdcrxisufnbyjegqmskzdqiyrdaefsbalhvjmacnunzgmilobmhsgypitihijmpkguwxeaicvcpsvgzyzflqyognu\nfclepxngurybwngiyzojoxvxihotoipmvkxfsdaq\nwioxghynzskvacpqlmfbdujretrm\nfmjbvnjgjqrmdexjdfbjirqiftypgpvlmcngolrfngiqrwtpsanzybkcvhhabuahb\nmymbfrbvrjtykklvtnkhaydgnlbuwktiemikrpxsoqskkgmatiqgyggbjlfrfynewzzedaxqgtphxsnjcwiyzyfyyrdjfxmxuc\neczouynjkfjiqrhaaivrrglycxeltuokqgfgjdltvpsavldsysnfbvwqdbhwusgtvwamtrvxeygxwbgsducp\nulyycfnoamjsowhechzuxrelkicqntcvwgwmkbdpitdxwvlezz\nlevddpeaxchbgsyqkrcbgboonujdefquepnlgpucrydonwxuautsufnmaeeadyshphbwbipzkmraqbubbnkc\nrcqbfyzfkahyjwrireqewpzxhweusejetvvyqmvndrimpzrxwbhmyjiyplakgbscpeoqkmrr\ncaqgmzrdvbtxdfmjotanbgaxrzqxboyiyhknypiiwaxealqzjevyalllcmjjuqfxnwjpmdlwxpaymipveljjsomdzq\nfzthexjxlsllqkusjqyrprhydeinadikssuvapqxuzjcetmlvsyfgnxonwrvgkipotxyevtojekpb\nhgmtzdbfarlwdlwsnyfcqsxtbmjbozelmnrvjngvpititekus\nzwzxqcemdkwfaoiraesaviyvpbjsldypobvailcebanhttqevtgwrbbdonubt\ndtiugjxdjlkbamfuldyhroknssoyycsmbmikbvuhwqhiflizzoeuyxrfptrgjfwmyv\ngzimamdjltbnoureicxhowvsfmqypksu\nfpgxbeqaiztkyfobrjvvmvpwdhsqclngezmu\nhougsdjedjacxbzytfcvcolevfoiktnxebupiwdupscjeekeaqrtgdbemodkl\nxwmksibzqymctvtcwbskgdhwtlcwhliqmbeioppxguqfansrxojveznizs\nhbzkivbrnuawesnofxudjqpkocbmlgbatmy\nquggkllvdcuspwqxisuofsezmtqjaximafykbchqztnrfbyonzs\nxygkfpedqvzztovaazinximtksophnaqrtrfhgkxlcoizkdjolowjgzqytuelbhcrbbtliwbejhploaksif\npqxkjufpwhphsqylipdegncaquoukbolwhoqafyahnrxrfwnymozzayooljozkvtwaofnunangqjiqjjruxzznfzmilusftuz\nfbhbvrnqtojnymfyrargfdccwuoyicqlatasneagomvnihxkgjwknijwtwmvufhpcauvtjyhikcqdez\nlklrbthlticrsiiqluepdbthzoggmshmffowxvskaamtxeinuxlwxrrendozdyfrdfjecojooom\nfvtxcsvtsifwcvoavqzubugourmhopkwzgmqbebtfnuvtjylodfcpwuooddvfaclcqmiazfmypkodprep\ndrscbotgyolpkjamfwbeuznceriqxvhmp\nktipdxlvdzywgajuoggehwdrmcaayclfbsqn\nxqucshkwdlqlehebzewdufhbhsycwkrlltljyjhnwpyjnlgwbnfrubaaesyalcvaldfqieodiwqxjpvgjqshnlpmzdgomj\nwwdcvolnnymnobvjcotgcrsddouufvaeiyqfplomwedxqhlrfmpedhvqsitoefrjrkgxneysztige\nltovwgcpjvpjiqgqtjxgbsjtptqzattomgfrbjrzbwycnbwgeebgnexmuhiouuhegyplcivzehdakahsofuerqkhhhri\nhfbsgpxkqjqrmekvdufmziaoylrctwqmon\novkjpgdnabqzwsqihzieifgiptgwyxrldtpudvczaqmpbjbhiravlfzeyteudggovdh\nlmczweoqihgxnjuoyvrbqaxupzwkvdscythgf\ncndcarmcjuixhrexjqvwubeymfavkvswelipckpnuskgopbsrwiuzdzvpddrnmljizbtvt\nvydxiuusmfkdgtrwcrublnwopzxfbrojhqgaee\nzwxpsvcqplkemgeoenjrihtubydabchof\nuzrpzgdqgkmwfxojfuwjgmidjykvtcarhhlniensmcqsxskxobtlasv\nomqxlzqrinyfkatnieawkbjggzuhkdiaspopkjojyfcfipmwtv\nsgeqpsdfzjbswsfqpicrxirakyhbvwxprrozunqmazhhsbtzal\nigqvlwmihxyvdbpfzsjarueonjfrtxck\nmqyainlpyerftcovkowzgkdjbxuhstsz\ntsyrbgefdzpvvcahnjkowxsilsumq\nfxtmkchbaqqeluzzkmrvoxpjpxyiaszxjttxnrdwbexascetg\neyefdbvkfvrpbhwpjmvmoiqkzrixhsmjkhizmnmlaoqpprowcmtzwtgzhryjulasfdltukiyymnpbdyuyugvoodtaczetlibwz\nhcjfxskbeblhmlzqmzvbrutfacwondphbgyjtnwwjupwcqjbebtpfsmvkiqigwzxbxxpx\nfgmqplrbaspwcukthavxqnzsyijoqed\ntkgahgslsqujjwhnpdnxkextirpvbhplqzpcpgniqucjwdfcudifwjzohravosjiamgvyldmfsabykh\njgepcfqnfhtevprhnaoskimcgyauvghuelyodqzidfjxfhmlcvtcmqbxikrofalmujorlwpoheucwmrvc\ndxighozubetqxvludodjrzgfgzqogwecptbwoynpascqowjlhzzwvmaiuvkzblifv\nrpjybciaklwgxzoeuvmjqhtndsf\nwgsdxqcsmlzjhrigzhnkkamevanvchhgokpgiyqtbadydylkqvgmwltxfussuuywi\ntnulqhbfwiojdwzmazgekltmxrkrnysivcqbph\njjefgnsxmbizjsialnymigtzbqhyojpyqpgyokinxjyhpyidsfrtjqczbmplqacmyenuwxuvzzreajezgfrgv\nyihzylpgwsfnbehtmdsktjjmoruaqszftcvxlg\npjykfhmmgpdwjsihqwoocbjxiumrzjotyeeafnevlpk'
const longArray = string.split('\n');

// const gemstones = arr => {
//     let count = 0;
//     const gems = {};
    
//     for (let i = 0; i < arr[0].length; i++){
//         if(!gems[arr[0][i]]) gems[arr[0][i]] = 1;
//     }

//     for (let i = 1; i < arr.length; i++){
//         const str = arr[i];

//         for(let gem in gems) {
//             if(str.includes(gem)) gems[gem]++;
//             if(gems[gem] === arr.length) count++;
//         }
//     }
//     return count;
// }

const gemstones = arr => {
    const gemCounts = new Set(arr[0]);
    for (let i = 1; i < arr.length; i++) {
        const currentGems = new Set(arr[i]);
        for (let gem of gemCounts) {
            if (!currentGems.has(gem)) gemCounts.delete(gem);
        }
    }
    return gemCounts.size;
}

console.log(gemstones(['abcdde', 'baccd', 'eeabg'])); //2
console.log(gemstones(['basdfj', 'asdlkjfdjsa','bnafvfnsd', 'oafhdlasd'])); //4
console.log(gemstones(['vtrjvgbj', 'mkmjyaeav','sibzdmsk']));//0
console.log(gemstones(longArray));//26

